name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Ninja
        run: choco install ninja

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build RelWithDebInfo
        run: |
          cmake --preset x86-relwithdebinfo
          cmake --build out/build/x86-relwithdebinfo

      - name: Build Release
        run: |
          cmake --preset x86-release
          cmake --build out/build/x86-release

      - name: Upload artifacts (RelWithDebInfo)
        uses: actions/upload-artifact@v7
        with:
          name: MafiaRE-RelWithDebInfo
          path: |
            out/build/x86-relwithdebinfo/*.asi
            out/build/x86-relwithdebinfo/*.pdb

      - name: Upload artifacts (Release)
        uses: actions/upload-artifact@v7
        with:
          name: MafiaRE-Release
          path: out/build/x86-release/*.asi